home:
    path: /
    handler: HomeController::home
    method: GET
login:
    path: /me-connecter
    handler: HomeController::login
    method: [GET, POST]
register:
    path: /m-enregistrer
    handler: HomeController::register
    method: GET

profile:
    path: /mon-profile
    handler: HomeController::profile
    method: GET